### ISSUE TITLE
A warning I met during I perform "python policy_run.py"

### ISSUE THREAD

**Issue by XiAoSSuper** [bilalkabas/PPO-based-Autonomous-Navigation-for-Quadcopters#1]
I have followed each step as suggested by the readme. However, I encounter the problem as follow:

WARNING:tornado.general:Connect error on fd 336: WSAECONNREFUSED
WARNING:tornado.general:Connect error on fd 336: WSAECONNREFUSED
WARNING:tornado.general:Connect error on fd 336: WSAECONNREFUSED
WARNING:tornado.general:Connect error on fd 336: WSAECONNREFUSED
WARNING:tornado.general:Connect error on fd 336: WSAECONNREFUSED
Traceback (most recent call last):
  File "policy_run.py", line 14, in <module>
    env = DummyVecEnv([lambda: Monitor(
  File "E:\Anaconda\envs\PPO_drone\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 25, in __init__
    self.envs = [fn() for fn in env_fns]
  File "E:\Anaconda\envs\PPO_drone\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 25, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "policy_run.py", line 15, in <lambda>
    gym.make(
  File "E:\Anaconda\envs\PPO_drone\lib\site-packages\gym\envs\registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "E:\Anaconda\envs\PPO_drone\lib\site-packages\gym\envs\registration.py", line 129, in make
    env = spec.make(**kwargs)
  File "E:\Anaconda\envs\PPO_drone\lib\site-packages\gym\envs\registration.py", line 90, in make
    env = cls(**_kwargs)
  File "E:\Project\PPO_based_ANfQ\PPO-based-Autonomous-Navigation-for-Quadcopters\scripts\airsim_env.py", line 169, in __init__
    super(TestEnv, self).__init__(ip_address, image_shape, env_config)
  File "E:\Project\PPO_based_ANfQ\PPO-based-Autonomous-Navigation-for-Quadcopters\scripts\airsim_env.py", line 19, in __init__
    self.setup_flight()
  File "E:\Project\PPO_based_ANfQ\PPO-based-Autonomous-Navigation-for-Quadcopters\scripts\airsim_env.py", line 174, in setup_flight
    super(TestEnv, self).setup_flight()
  File "E:\Project\PPO_based_ANfQ\PPO-based-Autonomous-Navigation-for-Quadcopters\scripts\airsim_env.py", line 36, in setup_flight
    self.drone.reset()
  File "E:\Project\PPO_based_ANfQ\PPO-based-Autonomous-Navigation-for-Quadcopters\scripts\airsim\client.py", line 26, in reset
    self.client.call('reset')
  File "E:\Anaconda\envs\PPO_drone\lib\site-packages\msgpackrpc\session.py", line 41, in call
    return self.send_request(method, args).get()
  File "E:\Anaconda\envs\PPO_drone\lib\site-packages\msgpackrpc\future.py", line 43, in get
    raise self._error
msgpackrpc.error.TransportError: Retry connection over the limit

I would be grateful if anyone could tell me how to fix this.

**Comment by bilalkabas** [comment]
Hi,

It seems like the Unreal environment was not opened up. Prior to running the script, you should download the environment from [releases](https://github.com/bilalkabas/PPO-based-Autonomous-Navigation-for-Quadcopters/releases/tag/v1.0.0-windows) and extract it. Then, open up the .exe file in that folder. This will open up an Unreal environment. Finally, you can run the script.
